### ISSUE TITLE
Pub get failed after than flutter upgrade

### ISSUE THREAD

**Issue by fatihmert** [dooboolab/flutter_inapp_purchase#225]
### Version of flutter_inapp_purchase

2.2.0

### Platforms you faced the error (IOS or Android or both?)

Both

### Expected behavior

The platform version of this module is causing problems, but I could not solve the reason.

### Actual behavior

After running `flutter pub get` I shouldn't get the error normally.

### Tested environment (Emulator? Real Device?)

Real: Samsung Galaxy S20, Redmi Note 7, iPhone 7+, iPhone 8, iPhone XR

### Steps to reproduce the behavior

```
flutter channel master
flutter upgrade
flutter pub get
```

Output

```
Because every version of flutter_driver from sdk depends on platform 3.0.0-nullsafety.2 and flutter_inapp_purchase 2.2.0 depends on platform ^2.2.1, flutter_driver from sdk is incompatible with flutter_inapp_purchase 2.2.0.
And because no versions of flutter_inapp_purchase match >2.2.0 <3.0.0, flutter_driver from sdk is incompatible with flutter_inapp_purchase ^2.2.0.
So, because key_rote depends on both flutter_inapp_purchase ^2.2.0 and flutter_driver any from sdk, version solving failed.
Running "flutter pub get" in myapp-name...      
pub get failed (1; So, because key_rote depends on both flutter_inapp_purchase
^2.2.0 and flutter_driver any from sdk, version solving failed.)
```

### Pubspec.yaml

```yaml
name: app_name
description: AppName - Description
version: 1.0.6+21

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^0.18.0
  http: ^0.12.0+4
  tinycolor: ^1.0.2
  get_it:
  provider: ^4.0.4
  shared_preferences: ^0.5.6+3
  percent_indicator: ^2.1.5
  audioplayers: ^0.16.1
  flutter_html: ^0.11.1
  flutter_native_splash: ^0.1.9
  fluttertoast: ^4.0.1
  flutter_inapp_purchase: ^2.2.0
  intro_slider: ^2.2.9
  device_info: ^0.4.2+2

  cupertino_icons: ^0.1.2
  flutter_launcher_icons: ^0.7.5

flutter_icons:
  image_path: "icon/launcher.png"
  android: true
  ios: true

flutter_native_splash:
  image: assets/splash.png
  color: "6236FF"

dev_dependencies:
  test: any
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
     - family: GROBOLD
       fonts:
         - asset: fonts/GROBOLD.ttf
     - family: Gilroy
       fonts:
         - asset: fonts/Gilroy-Black.ttf
         - asset: fonts/Gilroy-BlackItalic.ttf
           style: italic
         - asset: fonts/Gilroy-Bold.ttf
         - asset: fonts/Gilroy-BoldItalic.ttf
           style: italic
         - asset: fonts/Gilroy-ExtraBold.ttf
         - asset: fonts/Gilroy-ExtraBoldItalic.ttf
           style: italic
         - asset: fonts/Gilroy-ExtraLight.ttf
         - asset: fonts/Gilroy-ExtraLightItalic.ttf
           style: italic
         - asset: fonts/Gilroy-Heavy.ttf
         - asset: fonts/Gilroy-HeavyItalic.ttf
           style: italic
         - asset: fonts/Gilroy-Italic.ttf
           style: italic
         - asset: fonts/Gilroy-Light.ttf
         - asset: fonts/Gilroy-LightItalic.ttf
           style: italic
         - asset: fonts/Gilroy-Medium.ttf
         - asset: fonts/Gilroy-MediumItalic.ttf
           style: italic
         - asset: fonts/Gilroy-Regular.ttf
         - asset: fonts/Gilroy-SemiBold.ttf
         - asset: fonts/Gilroy-SemiBoldItalic.ttf
           style: italic
         - asset: fonts/Gilroy-ThinItalic.ttf
           style: italic
         - asset: fonts/Gilroy-Thin.ttf
```

### Flutter doctor output

**Windows Machine**

```
[√] Flutter (Channel master, 1.22.0-10.0.pre.340, on Microsoft Windows [Version 10.0.18362.959], locale en-US)
    • Flutter version 1.22.0-10.0.pre.340 at C:\src\flutter
    • Framework revision 1fef5912cf (5 days ago), 2020-09-23 21:37:08 -0700
    • Engine revision dd35b5b659
    • Dart version 2.10.0 (build 2.10.0-156.0.dev)


[!] Android toolchain - develop for Android devices (Android SDK version 30.0.0-rc2)
    • Android SDK at C:\Users\fatih\AppData\Local\Android\Sdk
    • Platform android-29, build-tools 30.0.0-rc2
    • ANDROID_HOME = C:\Users\fatih\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.49.2)
    • VS Code at C:\Users\fatih\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.14.1

[√] Connected device (3 available)
    • Venus GO (mobile) • 2811389118001055 • android-arm    • Android 8.1.0 (API 27)
    • Web Server (web)  • web-server       • web-javascript • Flutter Tools
    • Chrome (web)      • chrome           • web-javascript • Google Chrome 85.0.4183.121

! Doctor found issues in 1 category.
```

**Mac Machine**

```
[✓] Flutter (Channel master, 1.22.0-10.0.pre.341, on Mac OS X 10.15.5 19F101
    x86_64, locale tr-TR)
    • Flutter version 1.22.0-10.0.pre.341 at /Users/for/flutter
    • Framework revision 67f51e8ec2 (5 days ago), 2020-09-24 10:02:03 -0400
    • Engine revision dd35b5b659
    • Dart version 2.10.0 (build 2.10.0-156.0.dev)

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/for/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for
      more details.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.10.0.beta.1

[!] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.49.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.1

 
[!] Connected device                          
    ! No devices available
```
