### ISSUE TITLE
flutter_driver 1.25.5 compatibility

### ISSUE THREAD

**Issue by pmagnuson** [dooboolab/flutter_inapp_purchase#261]
### Version of flutter_inapp_purchase
flutter_inapp_purchase: ^3.0.1

### Platforms you faced the error (IOS or Android or both?)
both

### Expected behavior
`flutter pub get` runs with no errors 

### Actual behavior
when `flutter_driver` is added to `pub_spec.yaml`, the following error occurs
```
Because every version of flutter_driver from sdk depends on platform 3.0.0-nullsafety.2 and flutter_inapp_purchase 3.0.1 depends on platform ^2.2.1, flutter_driver from sdk is incompatible with flutter_inapp_purchase 3.0.1.

And because no versions of flutter_inapp_purchase match >3.0.1 <4.0.0, flutter_driver from sdk is incompatible with flutter_inapp_purchase ^3.0.1.

So, because BuddhaPath depends on both flutter_inapp_purchase ^3.0.1 and flutter_driver any from sdk, version solving failed.
pub get failed (1; So, because BuddhaPath depends on both flutter_inapp_purchase ^3.0.1 and flutter_driver any from sdk, version solving failed.)
exit code 1
```

### Tested environment (Emulator? Real Device?)
N/A

### Steps to reproduce the behavior
`pubspec.yaml`
```yaml
name: BuddhaPath
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.7.0+316

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  audioplayers: ^0.17.3
  connectivity: ^2.0.2
  csv: ">=4.0.3"
  cupertino_icons: ^1.0.0
  flutter_inapp_purchase: ^3.0.1
  googleapis: any
  googleapis_auth: ^0.2.12+1
  intl: ^0.16.1
  native_pdf_view: any
  package_info: ^0.4.0+18
  provider: ^4.3.3
  shared_preferences: ^0.5.7+2
  url_launcher: ^5.4.10

dev_dependencies:
  flutter_driver:
    sdk: flutter
  test: any
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.8.1
  # screenshots: "^2.1.1"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/
    - assets/pdf/bp/
    - assets/pdf/tfnt/
    - assets/pdf/se/
    - assets/audio/
    - assets/localization/

  fonts:
    - family: TimesNewRoman
      fonts:
        - asset: assets/fonts/timesnewroman.ttf
        - asset: assets/fonts/timesnewroman_italic.ttf
          style: italic
        - asset: assets/fonts/timesnewroman_bold.ttf
          weight: 700
        - asset: assets/fonts/timesnewroman_bold_italic.ttf
          style: italic
          weight: 700
    - family: NuptialScript
      fonts:
        - asset: assets/fonts/NuptialScript.ttf
 
```
`flutter doctor -v`
```
[✓] Flutter (Channel stable, 1.22.5, on Mac OS X 10.15.7 19H114 darwin-x64, locale en-US)
    • Flutter version 1.22.5 at /Users/phil/bin/flutter
    • Framework revision 7891006299 (10 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/phil/Library/Android/sdk
    • Platform android-30, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 41.1.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.53.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.19.0

[✓] Connected device (1 available)
    • PTM iPad (mobile) • 87132db6298fc2f271dd2785c026bb1d94dd1442 • ios • iOS 14.2

• No issues found!
```
